version: "3"
services:
  munro-pg:
    image: "postgres:latest"
    container_name: munro-pg
    env_file:
      - backend/.env
    ports:
      - 5432:5432
    volumes:
      - munro-pg-data:/var/lib/postgresql/data/
volumes:
  munro-pg-data:
